### ISSUE TITLE
available_ports() always empty

### ISSUE THREAD

**Issue by itsgoofer** [s00d/tauri-plugin-serialplugin#4]
Trying to get a list of serial ports on my PC. I have COM1, COM2 and COM3 opened, but the list is always empty.

```js
function ports() {
        SerialPort.available_ports()
            .then((res) => {
                console.log('available_ports: ', res);
            })
            .catch((err) => {
                console.error(err);
            });
    }
```
I'm getting `Serial port list: {}`

I have the plugin installed, declared in lib.rs and the permissions setup. 
Any ideas? 

Thanks.

**Comment by s00d** [comment]
Hello, the library used for working with ports is https://github.com/serialport/serialport-rs. In the available_ports method, there is only a filter for the port type; there is no other functionality. You will need to try to get the list of ports directly, and if the list is still empty, please contact the developer of the serialport-rs library, as the issue lies somewhere on the library's side.

**Comment by s00d** [comment]
It seems the issue may be related to the following discussions:
- [Issue #81](https://github.com/serialport/serialport-rs/issues/81)
- [Issue #128](https://github.com/serialport/serialport-rs/issues/128)

As of now, it appears that the problem has not been resolved. I recommend trying the [available_ports_direct](https://github.com/s00d/tauri-plugin-serialplugin?tab=readme-ov-file#serialportavailable_ports_direct) method for version 2.0.0-rc.4.

- **`available_ports_direct`**: This method serves as a fallback when `available_ports` fails. It directly executes system commands to list serial ports based on the operating system (Windows, Linux, macOS). It returns a list of detected ports with a default type of "Unknown."
