### ISSUE TITLE
<SerialPort>.listen() not working.

### ISSUE THREAD

**Issue by shunceyb** [s00d/tauri-plugin-serialplugin#6]
![image](https://github.com/user-attachments/assets/0c755e0f-5792-466f-9f61-31b78b863369)

![image](https://github.com/user-attachments/assets/3bfd6aa9-7bc9-4106-9e45-75ce1e68a20e)

Am I doing anything wrong? It does find the serial port, and I can write to it, but listening to it does not work (the callback does not get called). I've checked in the serial monitor, and I am getting data.

**Comment by nodserve** [comment]
I also encountered the same problem where Listen was unable to retrieve serial data

**Comment by s00d** [comment]
Try version 2.2.0; I moved the creation of the listener to open, whereas before it was in read, so it had to be called manually. Now, the listener should be created automatically. Unfortunately, I wasn't able to test it because my test device stopped working, and the library refuses to read virtual ports.

**Comment by nodserve** [comment]
![com](https://github.com/user-attachments/assets/a35830aa-00aa-4bbb-8891-04bced7aa9fa)
2.2.0 is now able to read data, which has been a great help to me. Thank you to the author.

**Comment by s00d** [comment]
Published version 2.3.1.
Moved the listener start to separate methods, `startListening` and `stopListening`, so that it can be restarted in case of issues. The listener no longer starts automatically upon connection; it only starts after calling `startListening`. Also made events global, just in case.

example: https://github.com/s00d/tauri-plugin-serialplugin/blob/5111138cbe2252f0e1580ab95e5bab50434c4561/examples/serialport-test/src/App.svelte#L71

**Comment by nodserve** [comment]
Thank you for the author's update. I will try version 2.3.1 later. Thank you again.

**Comment by shunceyb** [comment]
Sorry, it's still not working for me, only writing works still :(
![image](https://github.com/user-attachments/assets/ec2b0153-e708-4da1-85cb-cba7a1167b21)

Console output: 
![image](https://github.com/user-attachments/assets/b505c4f5-8491-42c2-9ade-d8ae1edef128)

Expected serial data(from serial monitor):
![image](https://github.com/user-attachments/assets/c994aba2-1c03-4194-b230-486927834da8)

Tested on windows, haven't tried on linux.

**Comment by shunceyb** [comment]
(Yes, I've updated to 2.3.1 on js and rust)

**Comment by shunceyb** [comment]
Okay, seems to be only an issue on windows; it works fine on Linux(Ubuntu). Should I close this?

**Comment by s00d** [comment]
> Okay, seems to be only an issue on windows; it works fine on Linux(Ubuntu). Should I close this?

if it’s as you described, the issue needs to be looked for in the library https://github.com/serialport/serialport-rs.

Basically, tauri-plugin-serialplugin is a wrapper for the serialport-rs library, and everything should work the same across all operating systems. If something doesn’t work, the issue likely lies in serialport-rs.
